// Auto-generated by scraper.py - do not edit manually
// Updated: 2026-09-11 23:19 - source: teplovsem.ru
// Gas boilers (dual/single circuit) + indirect water heaters + fixed boiler kit prices
window.BOILERS_LOCAL = {
  "updated": "2026-09-11T23:19:01.380044",
  "fixed": {
    "coaxial": 2900,
    "stabilizer": 5900,
    "pipe_m": 76,
    "fix": 102,
    "euro": 196,
    "iso_s": 27,
    "iso_r": 27,
    "obr34": 485,
    "btroj": 540,
    "kran12mm": 583,
    "troj34": 540,
    "bbak": 6000,
    "bbgrp": 3635,
    "kran34nv": 824,
    "bnasos": 2974,
    "bnipp1": 223,
    "kran34ff": 573,
    "fskob": 4,
    "pp32": 172,
    "filt34": 1047,
    "radpipe25": 107,
    "radopora25": 7,
    "ugl25": 17,
    "ugl2545": 17,
    "trj25": 22
  },
  "fixed_names": {
    "coaxial": "коаксиальный дымоход Baxi Bosch Protherm Комплект коаксиальный Антиобледенительное исп. 60/100",
    "stabilizer": "стабилизатор STOUT ST 600 SST-0001-000600",
    "pipe_m": "Труба сшитый полиэтилен ROMMER 16х2,0 PE-Xa (бухта 240 м) красная RPX-0002-241620",
    "fix": "Трубогибочный инструмент TIM Фиксатор поворота 16 FZ016-90",
    "euro": "Металлопластиковая труба TIM Евроконус 16 (2,0) мм x 3/4\" МП",
    "iso_s": "Теплоизоляция Энергофлекс SUPER PROTECT синий 018/06-2",
    "iso_r": "Теплоизоляция Энергофлекс SUPER PROTECT красный 018/06-2",
    "obr34": "Запорная арматура VIEIR Клапан обратного хода 3/4\" с металлическим седлом ZH674",
    "btroj": "Valtec Тройник переходной 3/4\"х1/2\"х3/4\" вн.-вн.-вн. VTr.750.N.0504",
    "kran12mm": "Запорная арматура Valtec Кран шаровой 1/2\" MM баб. Base VT.219.N.04",
    "troj34": "Valtec Тройник переходной 3/4\"х1/2\"х3/4\" вн.-вн.-вн. VTr.750.N.0504",
    "bbak": "гидроаккумулятор для водоснабже Flamco Airfix R 25 л",
    "bbgrp": "Предохранительная арматура TIM группа безопасности котла настенная 3 бара JH-1021",
    "kran34nv": "Запорная арматура Valtec Кран шаровой 3/4\" MF баб. Base VT.218.N.05",
    "bnasos": "циркуляционный насос AquaTim AM-XPS25-6-180",
    "bnipp1": "VIEIR Ниппель переходной 1\"х3/4\" нар.-нар. SH54",
    "kran34ff": "Запорная арматура Rommer Кран шаровый 3/4\" FF бабочка RBV-0003-2110220",
    "fskob": "Скобы-кассеты якорные для трубы 16-20 P1620-4",
    "pp32": "Труба ПП d 32 стекловолокно ProAqua Rubis Белая",
    "filt34": "Фильтр грубой очистки Valtec Фильтр грубой очистки 3/4\" VT.192.N.05",
    "radpipe25": "полипропиленовая труба ProAqua Труба d 25 Стекловолокно Rubis Белая",
    "radopora25": "полипропиленовая труба ProAqua Опора 25 Белая",
    "ugl25": "полипропиленовая труба ProAqua Уголок 25 90 Белый",
    "ugl2545": "полипропиленовая труба ProAqua Уголок 25 45 Белый",
    "trj25": "полипропиленовая труба ProAqua Тройник 25 Белый"
  },
  "boilers": [
    {
      "name": "Настенный газовый котел Baxi ECO Nova 14 F",
      "price": 48351,
      "kw": 14,
      "url": "/products/boilers/wallhung_gasboilers/3_23232_baxi_eco_nova_14_f.html"
    },
    {
      "name": "Настенный газовый котел Baxi ECO Nova 18 F",
      "price": 48957,
      "kw": 18,
      "url": "/products/boilers/wallhung_gasboilers/3_25824_baxi_eco_nova_18_f.html"
    },
    {
      "name": "Настенный газовый котел Baxi ECO Nova 24 F",
      "price": 50914,
      "kw": 24,
      "url": "/products/boilers/wallhung_gasboilers/3_22961_baxi_eco_nova_24_f.html"
    },
    {
      "name": "Настенный газовый котел Baxi Eco LIFE 24 F",
      "price": 50914,
      "kw": 24,
      "url": "/products/boilers/wallhung_gasboilers/3_26352_baxi_eco_life_24_f.html"
    },
    {
      "name": "Настенный газовый котел Baxi ECO-4S 10F",
      "price": 56667,
      "kw": 10,
      "url": "/products/boilers/wallhung_gasboilers/3_14893_baxi_eco-4s_10f.html"
    },
    {
      "name": "Настенный газовый котел Baxi ECO-4S 18F",
      "price": 59035,
      "kw": 18,
      "url": "/products/boilers/wallhung_gasboilers/3_14894_baxi_eco-4s_18f.html"
    },
    {
      "name": "Настенный газовый котел Baxi ECO-4S 24F",
      "price": 59460,
      "kw": 24,
      "url": "/products/boilers/wallhung_gasboilers/3_14892_baxi_eco-4s_24f.html"
    },
    {
      "name": "Настенный газовый котел Baxi ECO Nova 31 F",
      "price": 66828,
      "kw": 31,
      "url": "/products/boilers/wallhung_gasboilers/3_25302_baxi_eco_nova_31_f.html"
    },
    {
      "name": "Настенный газовый котел Baxi Eco LIFE 31 F",
      "price": 71160,
      "kw": 31,
      "url": "/products/boilers/wallhung_gasboilers/3_26353_baxi_eco_life_31_f.html"
    },
    {
      "name": "Настенный газовый котел Baxi Eco Four 24 F",
      "price": 72805,
      "kw": 24,
      "url": "/products/boilers/wallhung_gasboilers/3_4_baxi_eco_four_24_f.html"
    },
    {
      "name": "Настенный газовый котел Baxi Luna-3 240 Fi",
      "price": 85708,
      "kw": 24,
      "url": "/products/boilers/wallhung_gasboilers/3_1279_baxi_luna-3_240_fi.html"
    },
    {
      "name": "Настенный газовый котел Baxi Luna-3 Comfort 240 Fi",
      "price": 93729,
      "kw": 24,
      "url": "/products/boilers/wallhung_gasboilers/3_10_baxi_luna-3_comfort_240_fi.html"
    },
    {
      "name": "Настенный газовый котел Baxi Luna-3 280 Fi",
      "price": 95160,
      "kw": 28,
      "url": "/products/boilers/wallhung_gasboilers/3_1278_baxi_luna-3_280_fi.html"
    },
    {
      "name": "Настенный газовый котел Baxi Luna-3 310 Fi",
      "price": 97363,
      "kw": 31,
      "url": "/products/boilers/wallhung_gasboilers/3_1277_baxi_luna-3_310_fi.html"
    }
  ],
  "boilers1": [
    {
      "name": "Настенный газовый котел Baxi Eco LIFE 1.24 F",
      "price": 52034,
      "kw": 24,
      "url": "/products/boilers/wallhung_gasboilers/3_26354_baxi_eco_life_1_24_f.html"
    },
    {
      "name": "Настенный газовый котел Baxi Eco Four 1.14 F",
      "price": 61568,
      "kw": 14,
      "url": "/products/boilers/wallhung_gasboilers/3_7_baxi_eco_four_1_14_f.html"
    },
    {
      "name": "Настенный газовый котел Baxi Eco Four 1.24 F",
      "price": 65037,
      "kw": 24,
      "url": "/products/boilers/wallhung_gasboilers/3_8_baxi_eco_four_1_24_f.html"
    },
    {
      "name": "Настенный газовый котел Baxi Eco LIFE 1.31 F",
      "price": 70124,
      "kw": 31,
      "url": "/products/boilers/wallhung_gasboilers/3_26355_baxi_eco_life_1_31_f.html"
    },
    {
      "name": "Настенный газовый котел Baxi Luna-3 1.310 Fi",
      "price": 83752,
      "kw": 31,
      "url": "/products/boilers/wallhung_gasboilers/3_1281_baxi_luna-3_1_310_fi.html"
    },
    {
      "name": "Настенный газовый котел Baxi Luna-3 Comfort 1.240 Fi",
      "price": 84367,
      "kw": 24,
      "url": "/products/boilers/wallhung_gasboilers/3_13_baxi_luna-3_comfort_1_240_fi.html"
    },
    {
      "name": "Настенный газовый котел Baxi Luna-3 Comfort 1.310 Fi",
      "price": 91361,
      "kw": 31,
      "url": "/products/boilers/wallhung_gasboilers/3_14_baxi_luna-3_comfort_1_310_fi.html"
    }
  ],
  "heaters": [
    {
      "name": "Водонагреватель косвенного нагрева Baxi UBT 80(GR)",
      "price": 43678,
      "litres": 80,
      "mat": "em",
      "maker": "Baxi",
      "url": "/products/boilers_indirect/enameled/57_22885_baxi_ubt_80gr.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Baxi UB 80",
      "price": 68651,
      "litres": 80,
      "mat": "em",
      "maker": "Baxi",
      "url": "/products/boilers_indirect/enameled/57_792_baxi_ub_80.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Baxi UBT 100(GR)",
      "price": 46439,
      "litres": 100,
      "mat": "em",
      "maker": "Baxi",
      "url": "/products/boilers_indirect/enameled/57_22886_baxi_ubt_100gr.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Baxi UBT 120(GR)",
      "price": 51472,
      "litres": 120,
      "mat": "em",
      "maker": "Baxi",
      "url": "/products/boilers_indirect/enameled/57_22887_baxi_ubt_120gr.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Baxi UB 120",
      "price": 79790,
      "litres": 120,
      "mat": "em",
      "maker": "Baxi",
      "url": "/products/boilers_indirect/enameled/57_794_baxi_ub_120.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Baxi UBT 160(GR)",
      "price": 61972,
      "litres": 160,
      "mat": "em",
      "maker": "Baxi",
      "url": "/products/boilers_indirect/enameled/57_22888_baxi_ubt_160gr.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Baxi UBT 200(GR)",
      "price": 64029,
      "litres": 200,
      "mat": "em",
      "maker": "Baxi",
      "url": "/products/boilers_indirect/enameled/57_22889_baxi_ubt_200gr.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Baxi UBT 300(GR)",
      "price": 94988,
      "litres": 300,
      "mat": "em",
      "maker": "Baxi",
      "url": "/products/boilers_indirect/enameled/57_22890_baxi_ubt_300gr.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu AQ IND FC 75 настенный",
      "price": 50436,
      "litres": 75,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_13908_hajdu_aq_ind_fc_75_nastennyy.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu ID 20 A",
      "price": 37490,
      "litres": 80,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_21187_hajdu_id_20_a.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu ID 25 A",
      "price": 41805,
      "litres": 100,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_21188_hajdu_id_25_a.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu AQ IND FC 100 настенный",
      "price": 54886,
      "litres": 100,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_13909_hajdu_aq_ind_fc_100_nastennyy.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu IND100SC",
      "price": 63652,
      "litres": 100,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_13912_hajdu_aq_ind_sc_100.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu HR-T 30",
      "price": 34096,
      "litres": 120,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16809_hajdu_hr-t_30.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu HR-N 30",
      "price": 87792,
      "litres": 120,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16813_hajdu_hr-n_30.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu ID 40 A",
      "price": 48953,
      "litres": 150,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_21189_hajdu_id_40_a.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu AQ IND FC 150 настенный",
      "price": 62439,
      "litres": 150,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_13910_hajdu_aq_ind_fc_100_nastennyy.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu IND150SC",
      "price": 71204,
      "litres": 150,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_13913_hajdu_aq_ind_sc_150.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu AQ IND 150 SC",
      "price": 71204,
      "litres": 150,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16812_hajdu_aq_ind_150sc.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu HR-N 40",
      "price": 91971,
      "litres": 160,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16814_hajdu_hr-n_40.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu ID 50 A",
      "price": 56101,
      "litres": 190,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_21190_hajdu_id_50_a.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu AQ IND FC 200 настенный",
      "price": 71204,
      "litres": 200,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_13911_hajdu_aq_ind_fc_200_nastennyy.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu IND200SC",
      "price": 80239,
      "litres": 200,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_13914_hajdu_aq_ind_sc_200.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu AQ IND 200 SC",
      "price": 80239,
      "litres": 200,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16811_hajdu_aq_ind_200sc.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu STA200C",
      "price": 91028,
      "litres": 200,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16795_hajdu_sta200c.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu STA200C2",
      "price": 113414,
      "litres": 200,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16802_hajdu_sta200c2.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu STA300C",
      "price": 115571,
      "litres": 300,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16796_hajdu_sta300c.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu STA300C2",
      "price": 141868,
      "litres": 300,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16804_hajdu_sta300c2.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu STA400C2",
      "price": 213207,
      "litres": 400,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16805_hajdu_sta400c2.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu STA500C",
      "price": 226962,
      "litres": 500,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16798_hajdu_sta500c.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu STA500C2",
      "price": 249483,
      "litres": 500,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16806_hajdu_sta500c2.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu STA800C",
      "price": 315293,
      "litres": 800,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16799_hajdu_sta800c.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu STA800C2",
      "price": 341994,
      "litres": 800,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16807_hajdu_sta800c2.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu STA1000C",
      "price": 376112,
      "litres": 1000,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16800_hajdu_sta1000c.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Hajdu STA1000C2",
      "price": 399173,
      "litres": 1000,
      "mat": "em",
      "maker": "Hajdu",
      "url": "/products/boilers_indirect/enameled/57_16808_hajdu_sta1000c2.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева STOUT Комбинированный настенный 75 л,ТЭН 2,4 кВт SWH-1210-050075",
      "price": 59000,
      "litres": 75,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_27164_stout_kombinirovannyy_nastennyy_.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева STOUT Комбинированный настенный 100 л,ТЭН 2,4 кВт SWH-1210-050100",
      "price": 62000,
      "litres": 100,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_27165_stout_kombinirovannyy_nastennyy_.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева STOUT Комбинированный напольный 100 л, один теплообменник, ТЭН 2 кВт SWH-1110-050100",
      "price": 69000,
      "litres": 100,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_26439_stout_kombinirovannyy_napolnyy_1.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Stout OptiBase 150 напольный SWH-2110-000150",
      "price": 45500,
      "litres": 150,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_28707_stout_optibase_150_napolnyy_swh-.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева STOUT бойлер косвенного нагрева напольный 150 л SWH-1110-000150 (без ТЭНа)",
      "price": 63852,
      "litres": 150,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_26988_stout_boyler_kosvennogo_nagreva_.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева STOUT Комбинированный настенный 150 л,ТЭН 2,4 кВт SWH-1210-050150",
      "price": 69000,
      "litres": 150,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_27166_stout_kombinirovannyy_nastennyy_.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева STOUT Комбинированный напольный 150 л, один теплообменник, ТЭН 2 кВт SWH-1110-050150",
      "price": 77000,
      "litres": 150,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_26438_stout_kombinirovannyy_napolnyy_1.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Stout OptiBase 200 напольный SWH-2110-000200",
      "price": 51000,
      "litres": 200,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_28706_stout_optibase_200_napolnyy_swh-.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Stout OptiBase 200 напольный два теплообменника SWH-2110-200200",
      "price": 64000,
      "litres": 200,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_28705_stout_optibase_200_napolnyy_dva_.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева STOUT бойлер косвенного нагрева напольный 200 л SWH-1110-000200 (без ТЭНа)",
      "price": 68965,
      "litres": 200,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_26987_stout_boyler_kosvennogo_nagreva_.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева STOUT Комбинированный настенный 200 л,ТЭН 2,4 кВт SWH-1210-050200",
      "price": 78000,
      "litres": 200,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_27167_stout_kombinirovannyy_nastennyy_.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева STOUT Комбинированный напольный 200 л, один теплообменник, ТЭН 3 кВт SWH-1110-050200",
      "price": 85000,
      "litres": 200,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_26437_stout_kombinirovannyy_napolnyy_2.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Stout OptiBase 300 напольный SWH-2110-000300",
      "price": 79000,
      "litres": 300,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_28708_stout_optibase_300_napolnyy_swh-.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева Stout OptiBase 300 напольный два теплообменника SWH-2110-200300",
      "price": 85000,
      "litres": 300,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_28704_stout_optibase_300_napolnyy_dva_.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева STOUT Комбинированный напольный 300 л, один теплообменник, ТЭН 3 кВт SWH-1110-050300",
      "price": 111000,
      "litres": 300,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_26436_stout_kombinirovannyy_napolnyy_3.html"
    },
    {
      "name": "Водонагреватель косвенного нагрева STOUT Комбинированный напольный 300 л, два теплообменника, ТЭН 3 кВт SWH-1110-250300",
      "price": 121000,
      "litres": 300,
      "mat": "em",
      "maker": "Stout",
      "url": "/products/boilers_indirect/enameled/57_26440_stout_kombinirovannyy_napolnyy_3.html"
    },
    {
      "name": "нержавейка Baxi premier plus 100",
      "price": 80483,
      "litres": 100,
      "mat": "ss",
      "maker": "Baxi",
      "url": "/products/boilers_indirect/boilers_steel/56_563_baxi_premier_plus_100.html"
    },
    {
      "name": "нержавейка Baxi premier plus 150",
      "price": 86545,
      "litres": 150,
      "mat": "ss",
      "maker": "Baxi",
      "url": "/products/boilers_indirect/boilers_steel/56_564_baxi_premier_plus_150.html"
    },
    {
      "name": "нержавейка Baxi premier plus 200",
      "price": 101266,
      "litres": 200,
      "mat": "ss",
      "maker": "Baxi",
      "url": "/products/boilers_indirect/boilers_steel/56_565_baxi_premier_plus_200.html"
    },
    {
      "name": "нержавейка Baxi premier plus 300",
      "price": 122158,
      "litres": 300,
      "mat": "ss",
      "maker": "Baxi",
      "url": "/products/boilers_indirect/boilers_steel/56_566_baxi_premier_plus_300.html"
    },
    {
      "name": "нержавейка Gekon(RISPA) HWB 120 1HE TC INOX",
      "price": 76506,
      "litres": 120,
      "mat": "ss",
      "maker": "Gekon",
      "url": "/products/boilers_indirect/boilers_steel/56_26528_gekon_hwb_120_1he_tc_inox.html"
    },
    {
      "name": "нержавейка Gekon(RISPA) HWB 150 1HE INOX",
      "price": 72203,
      "litres": 150,
      "mat": "ss",
      "maker": "Gekon",
      "url": "/products/boilers_indirect/boilers_steel/56_26521_gekon_hwb_150_1he_inox.html"
    },
    {
      "name": "нержавейка Gekon(RISPA) HWB 200 1HE INOX",
      "price": 79871,
      "litres": 200,
      "mat": "ss",
      "maker": "Gekon",
      "url": "/products/boilers_indirect/boilers_steel/56_26522_gekon_hwb_200_1he_inox.html"
    },
    {
      "name": "нержавейка Gekon(RISPA) HWB 200 2HE INOX",
      "price": 92525,
      "litres": 200,
      "mat": "ss",
      "maker": "Gekon",
      "url": "/products/boilers_indirect/boilers_steel/56_26525_gekon_hwb_200_2he_inox.html"
    },
    {
      "name": "нержавейка Gekon(RISPA) HWB 300 1HE INOX",
      "price": 111596,
      "litres": 300,
      "mat": "ss",
      "maker": "Gekon",
      "url": "/products/boilers_indirect/boilers_steel/56_26523_gekon_hwb_300_1he_inox.html"
    },
    {
      "name": "нержавейка Gekon(RISPA) HWB 300 2HE INOX",
      "price": 131024,
      "litres": 300,
      "mat": "ss",
      "maker": "Gekon",
      "url": "/products/boilers_indirect/boilers_steel/56_26526_gekon_hwb_300_2he_inox.html"
    },
    {
      "name": "нержавейка Gekon(RISPA) HWB 400 1HE INOX",
      "price": 126365,
      "litres": 400,
      "mat": "ss",
      "maker": "Gekon",
      "url": "/products/boilers_indirect/boilers_steel/56_26524_gekon_hwb_400_1he_inox.html"
    },
    {
      "name": "нержавейка Gekon(RISPA) HWB 400 2HE INOX",
      "price": 145793,
      "litres": 400,
      "mat": "ss",
      "maker": "Gekon",
      "url": "/products/boilers_indirect/boilers_steel/56_26527_gekon_hwb_400_2he_inox.html"
    }
  ]
};
