// Auto-generated by scraper.py - do not edit manually
// Updated: 2026-09-11 21:59 - source: teplovsem.ru
// Calculator reads this file and overrides hardcoded prices
window.PRICES_LOCAL = {
  "1/2\"": {
    "kran": {
      "price": 713,
      "name": "Запорная арматура Itap Кран шаровый со штуцером 1/2&quot; руч. 166",
      "url": "/products/pipes/stop_valve/121_13235_itap_kran_sharovyy_so_shtutserom.html",
      "category": "pipes/stop_valve"
    },
    "murfa_nr": {
      "price": 74,
      "name": "VIEIR Ниппель переходной 1/2&quot;х1/4&quot; нар.-нар. SH31",
      "url": "/products/pipes/brass_fittings/123_14582_vieir_nippel_perehodnoy_3_4h1_2.html",
      "category": "pipes/brass_fittings"
    },
    "murfa_vr": {
      "price": 135,
      "name": "VIEIR Муфта 1/2&quot; SF33",
      "url": "/products/pipes/brass_fittings/123_14609_vieir_gaika_perehodnoy.html",
      "category": "pipes/brass_fittings"
    },
    "ugolok": {
      "price": 196,
      "name": "VIEIR Угольник 1/2&quot; ВН.-ВН. LF33",
      "url": "/products/pipes/brass_fittings/123_14772_vieir_gaika_perehodnoy.html",
      "category": "pipes/brass_fittings"
    },
    "trojnik": {
      "price": 238,
      "name": "VIEIR Тройник 1/2&quot;x1/2&quot;x1/2&quot; TF333",
      "url": "/products/pipes/brass_fittings/123_14776_vieir_gaika_perehodnoy.html",
      "category": "pipes/brass_fittings"
    },
    "sgon": {
      "price": 110,
      "name": "Valtec Удлинитель 1/2&quot; х 10 мм VTr.197.N.0410",
      "url": "/products/pipes/brass_fittings/123_13289_valtec_udlinitel_1_2_h_10_mm_vtr.html",
      "category": "pipes/brass_fittings"
    },
    "kontr": {
      "price": 51,
      "name": "Valtec Контргайка 1/2&quot; VTr.655.N.0004",
      "url": "/products/pipes/brass_fittings/123_13279_valtec_kontrgayka_1_2_vtr_655_n_.html",
      "category": "pipes/brass_fittings"
    },
    "zaglushka": {
      "price": 95,
      "name": "Valtec Заглушка ВН. 1/2&quot; VTr.590.N.0004",
      "url": "/products/pipes/brass_fittings/123_8007_valtec_zaglushka_vn_1_2_vtr_590_.html",
      "category": "pipes/brass_fittings"
    },
    "fum": {
      "price": 36,
      "name": "Уплотнительный материал Terma GAS 12 м * 12мм* 0,1 мм",
      "url": "/products/tool/sealing_materials/126_14476_terma_big_gas_10_m_19mm_02_mm.html",
      "category": "tool/sealing_materials"
    },
    "pasta": {
      "price": 323,
      "name": "Уплотнительный материал Паста герметик 250 г.",
      "url": "/products/tool/sealing_materials/126_20630_pasta_germetik_250_g_.html",
      "category": "tool/sealing_materials"
    }
  },
  "3/4\"": {
    "kran": {
      "price": 833,
      "name": "Запорная арматура Rommer Кран шаровый с н/г 3/4&quot; MF бабочка RBV-0005-2510220",
      "url": "https://www.teplovsem.ru/products/pipes/stop_valve/121_24915_rommer_kran_sharovyy_s_n_g_3_4_m.html",
      "category": "pipes/stop_valve"
    },
    "murfa_nr": {
      "price": 143,
      "name": "VIEIR Ниппель переходной 3/4&quot;х1/2&quot; нар.-нар. SH34",
      "url": "/products/pipes/brass_fittings/123_14631_vieir_nippel_perehodnoy_3_4h1_2.html",
      "category": "pipes/brass_fittings"
    },
    "murfa_vr": {
      "price": 172,
      "name": "VIEIR Муфта переходная 3/4&quot;х1/2&quot; вн.-вн. SF34",
      "url": "/products/pipes/brass_fittings/123_14603_vieir_gaika_perehodnoy.html",
      "category": "pipes/brass_fittings"
    },
    "ugolok": {
      "price": 238,
      "name": "VIEIR Угольник 3/4&quot; ВН.-ВН. LF44",
      "url": "/products/pipes/brass_fittings/123_14778_vieir_gaika_perehodnoy.html",
      "category": "pipes/brass_fittings"
    },
    "trojnik": {
      "price": 303,
      "name": "VIEIR Тройник 3/4&quot;x1/2&quot;x3/4&quot; TF434",
      "url": "/products/pipes/brass_fittings/123_14773_vieir_gaika_perehodnoy.html",
      "category": "pipes/brass_fittings"
    },
    "sgon": {
      "price": 366,
      "name": "Valtec Удлинитель ХРОМ 3/4&quot; x 20 мм VTr.198.C.0520",
      "url": "/products/pipes/brass_fittings/123_13297_valtec_udlinitel_hrom_3_4_x_20_m.html",
      "category": "pipes/brass_fittings"
    },
    "kontr": {
      "price": 107,
      "name": "Valtec Контргайка 3/4&quot; VTr.655.N.0005",
      "url": "/products/pipes/brass_fittings/123_13280_valtec_kontrgayka_3_4_vtr_655_n_.html",
      "category": "pipes/brass_fittings"
    },
    "zaglushka": {
      "price": 82,
      "name": "VIEIR Пробка НАР. 3/4&quot; DTH4",
      "url": "/products/pipes/brass_fittings/123_16437_vieir_gaika_perehodnoy.html",
      "category": "pipes/brass_fittings"
    },
    "fum": {
      "price": 36,
      "name": "Уплотнительный материал Terma GAS 12 м * 12мм* 0,1 мм",
      "url": "/products/tool/sealing_materials/126_14476_terma_big_gas_10_m_19mm_02_mm.html",
      "category": "tool/sealing_materials"
    },
    "pasta": {
      "price": 323,
      "name": "Уплотнительный материал Паста герметик 250 г.",
      "url": "/products/tool/sealing_materials/126_20630_pasta_germetik_250_g_.html",
      "category": "tool/sealing_materials"
    }
  },
  "1\"": {
    "murfa_nr": {
      "price": 198,
      "name": "VIEIR Ниппель переходной 1&quot;х1/2&quot; нар.-нар. SH53",
      "url": "/products/pipes/brass_fittings/123_14584_vieir_nippel_perehodnoy_3_4h1_2.html",
      "category": "pipes/brass_fittings"
    },
    "murfa_vr": {
      "price": 210,
      "name": "VIEIR Муфта переходная 1&quot;х1/2&quot; вн.-вн. SF53",
      "url": "/products/pipes/brass_fittings/123_14604_vieir_gaika_perehodnoy.html",
      "category": "pipes/brass_fittings"
    },
    "ugolok": {
      "price": 430,
      "name": "VIEIR Угольник 1&quot; ВН.-ВН. LF55",
      "url": "/products/pipes/brass_fittings/123_17952_vieir_ugolnik_1_vn_-vn_.html",
      "category": "pipes/brass_fittings"
    },
    "trojnik": {
      "price": 496,
      "name": "VIEIR Тройник 1&quot; x3/4&quot;x1&quot; TF545",
      "url": "/products/pipes/brass_fittings/123_16435_vieir_gaika_perehodnoy.html",
      "category": "pipes/brass_fittings"
    },
    "kontr": {
      "price": 109,
      "name": "Valtec Контргайка 1&quot; VTr.655.N.0006",
      "url": "/products/pipes/brass_fittings/123_16016_valtec_kontrgayka_1_vtr_655_n_00.html",
      "category": "pipes/brass_fittings"
    },
    "zaglushka": {
      "price": 148,
      "name": "VIEIR Заглушка ВН. 1&quot; GMF5",
      "url": "/products/pipes/brass_fittings/123_14630_vieir_zaglushka_vn_1.html",
      "category": "pipes/brass_fittings"
    },
    "fum": {
      "price": 36,
      "name": "Уплотнительный материал Terma GAS 12 м * 12мм* 0,1 мм",
      "url": "/products/tool/sealing_materials/126_14476_terma_big_gas_10_m_19mm_02_mm.html",
      "category": "tool/sealing_materials"
    },
    "pasta": {
      "price": 323,
      "name": "Уплотнительный материал Паста герметик 250 г.",
      "url": "/products/tool/sealing_materials/126_20630_pasta_germetik_250_g_.html",
      "category": "tool/sealing_materials"
    },
    "kran": {
      "price": 1437,
      "name": "Запорная арматура Rommer Кран шаровый с н/г 1&quot; MF бабочка RBV-0005-2510225",
      "url": "https://www.teplovsem.ru/products/pipes/stop_valve/121_24913_rommer_kran_sharovyy_s_n_g_1_mf_.html",
      "category": "pipes/stop_valve"
    }
  }
};
